### ISSUE TITLE
Error: Failed to authenticate, have you run firebase login?

### ISSUE THREAD

**Issue by mhelfer** [burhankhanzada/firebase_app_distribution_github_action#7]
I have this in my build file

 - name: upload to Firebase App Distribution
        uses: nickwph/firebase-app-distribution-action@v1
        with:
          file: build/app/outputs/flutter-apk/app-release.apk
          app: spidersolitare-a75be
          testers: alltesters
          debug: true
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}

------

which produces this runtime errror

Run nickwph/firebase-app-distribution-action@v1
Run actions/cache@v3
  
Cache not found for input keys: firebase-tools
Run if ! command -v firebase &> /dev/null; then
  
fold: write error: Broken pipe
-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest

######################################################################## 100.0%#=#=#                                                                         
##=#=#                                                                        
##=O#- #                                                                      
#-#O=#  #                                                                     
 #=#=-#   #                                                                   

                                                                           0.0%
######################################################################## 100.0%
-- Setting permissions on binary...
-- Checking your PATH variable...
-- firebase-tools@12.9.1 is now installed
-- All Done!
Run $(which firebase) appdistribution:distribute \
[2023-11-16T05:59:[14](https://github.com/threetenlabs/spidersolitaire/actions/runs/6886892995/job/18733248487#step:8:15).235Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2023-11-16T05:59:14.264Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/home/runner/.cache/firebase/tools/lib/node_modules/google-auth-library/build/src/auth/googleauth.js:183:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GoogleAuth.getClient (/home/runner/.cache/firebase/tools/lib/node_modules/google-auth-library/build/src/auth/googleauth.js:565:17)
    at async GoogleAuth.getAccessToken (/home/runner/.cache/firebase/tools/lib/node_modules/google-auth-library/build/src/auth/googleauth.js:587:24)
    at async autoAuth (/home/runner/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/requireAuth.js:25:19)
    at async Object.requireAuth [as fn] (/home/runner/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/requireAuth.js:65:20)
    at async /home/runner/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/command.js:226:17

Error: Failed to authenticate, have you run firebase login?
[2023-11-16T05:59:14.353Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[2023-11-16T05:59:14.353Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":159425[28](https://github.com/threetenlabs/spidersolitaire/actions/runs/6886892995/job/18733248487#step:8:30)00000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390[40](https://github.com/threetenlabs/spidersolitaire/actions/runs/6886892995/job/18733248487#step:8:42)0000,"node8RuntimeDisabledAfter":161[58](https://github.com/threetenlabs/spidersolitaire/actions/runs/6886892995/job/18733248487#step:8:61)09[60](https://github.com/threetenlabs/spidersolitaire/actions/runs/6886892995/job/18733248487#step:8:63)0000,"node8WarnAfter":1600128000000}
Error: Process completed with exit code 1.

Any ideas?

**Comment by mhelfer** [comment]
Sorry I think this was my fault and I had the wrong secret variable
